config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  root "store#index", as: "store_index"
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    # line_items.to_a.sum { |item| item.total_price }
    line_items.to_a.sum(&:total_price)
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :description, :image_url, presence: true
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: { with: /\.(gif|jpg|png)\z/i,
                                                     message: "must be a URL for GIF, JPG or PNG image." }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  private

  # ensure that there are no line items referencing this product 
  def ensure_not_referenced_by_any_line_item
    return if line_items.empty?

    errors.add(:base, "Line item(s) present")
    throw :abort
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[show edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show; end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit; end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url, notice: "Your cart is currently empty" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cart_params
    params.fetch(:cart, {})
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to store_index_url, notice: "Invalid cart"
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart

  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: %i[show edit update destroy]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show; end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit; end

  # POST /line_items or /line_items.json
  def create
    # @line_item = LineItem.new(line_item_params)
    product = Product.find(params[:product_id])
    # @line_item = @cart.line_items.build(product: product)
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        # format.html { redirect_to @line_item.cart }
        format.html { redirect_to store_index_url }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def line_item_params
    params.require(:line_item).permit(:product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:title, :description, :image_url, :price)
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def index
    @products = Product.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
<article>
  <% if notice %>
    <aside id="notice"><%= notice %></aside>
  <% end %>

  <h2>Your Cart</h2>
  <table>
    <%= render(cart.line_items) %>
    <tfoot>
    <tr>
      <th colspan="2">Total:</th>
      <td class="price"><%= number_to_currency(cart.total_price) %></td>
    </tr>
    </tfoot>
  </table>
  <%= button_to 'Empty cart', cart, method: :delete, data: { confirm: 'Are you sure?' } %>
</article>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<%=render(@cart) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DepotRor</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
<header class="main">
  <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
  <h1><%= @page_title %></h1>
</header>
<section class="content">
  <nav class="side_nav">
    <% if @cart %>
      <div id="cart" class="carts">
        <%= render @cart %>
      </div>
    <% end %>
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="#">Questions</a></li>
      <li><a href="#">News</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </nav>
  <main class='<%= controller.controller_name %>'>
    <%= yield %>
  </main>
</section>
</body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
  <td class="quantity"><%= line_item.quantity %></td>
  <td><%= line_item.product.title %></td>
  <td class="price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/edit.html.erb
<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show this line item", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New line item", new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @line_item %>

<div>
  <%= link_to "Edit this line item", edit_line_item_path(@line_item) %> |
  <%= link_to "Back to line items", line_items_path %>

  <%= button_to "Destroy this line item", @line_item, method: :delete %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, rows: 10, cols: 60 %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= product.image_url %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Products</h1>

<table>
  <tfoot>
  <tr>
    <td colspan="3">
      <%= link_to 'New Product', new_product_path %>
    </td>
  </tr>
  </tfoot>
  <tbody>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

      <td class="image">
        <%= image_tag(product.image_url, class: 'list_image') %>
      </td>

      <td class="description">
        <h1><%= product.title %></h1>
        <p>
          <%= truncate(strip_tags(product.description),
                       length: 80) %>
        </p>
      </td>

      <td class="actions">
        <ul>
          <li><%= link_to 'Show', product %></li>
          <li><%= link_to 'Edit', edit_product_path(product) %></li>
          <li>
            <%= link_to 'Destroy',
                        product,
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
          </li>
        </ul>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/store/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Your Pragmatic Catalog</h1>

<ul class="catalog">
  <% cache @products do %>
    <% @products.each do |product| %>
      <% cache product do %>
        <li>
          <%= image_tag(product.image_url) %>
          <h2><%= product.title %></h2>
          <p>
            <%= sanitize(product.description) %>
          </p>
          <div class="price">
            <%= number_to_currency(product.price) %>
            <%= button_to "Add to Cart", line_items_path(product_id: product) %>
          </div>
        </li>
      <% end %>
    <% end %>
  <% end %>
</ul>